### ISSUE TITLE
Embedded navigation does not start navigation

### ISSUE THREAD

**Issue by fabiolin** [nick92/flutter_mapbox#6]
It makes the route, but the navigation does not start

**Comment by nick92** [comment]
Are you able to share the code that you're using? or are you just using the example code?

**Comment by fabiolin** [comment]
I am using the following code:

MapBoxNavigationView(
                    options: MapBoxOptions(
                        initialLatitude: -16.715928922800856,
                        initialLongitude: -49.29239587178779,
                        zoom: 13.0,
                        // tilt: 0.0,
                        // bearing: 0.0,
                        enableRefresh: false,
                        alternatives: true,
                        voiceInstructionsEnabled: false,
                        bannerInstructionsEnabled: true,
                        allowsUTurnAtWayPoints: true,
                        mode: MapBoxNavigationMode.drivingWithTraffic,
                        // mapStyleUrlDay: "https://url_to_day_style",
                        // mapStyleUrlNight: "https://url_to_night_style",
                        units: VoiceUnits.metric,
                        simulateRoute: false,
                        language: "pt_BR"),
                    onRouteEvent: _onRouteEvent,
                    onCreated:
                        (MapBoxNavigationViewController controller) async {
                      _controller = controller;

                      await controller.buildRoute(wayPoints: wayPoints);
                      await _controller!.startNavigation();
                    })

**Comment by fabiolin** [comment]
it looks like the navigation occurs in the background, i can hear the instruction as I navigate

**Comment by alpeshshiyal** [comment]
> it looks like the navigation occurs in the background, i can hear the instruction as I navigate

Have you find any solution for this issue?

**Comment by nick92** [comment]
this issue should now be resolved in v0.5.4 - it was starting the navigation but just not displaying it back correctly 

so now you should be able to activate the embedded navigation
